### ISSUE TITLE
Database Entity Updates

### ISSUE THREAD

**Issue by jeffkinnison** [tesserae/tesserae-v5#14]
I've been tinkering, and I propose the following changes to the database entries:

Existing Entities in `tesserae.db.entities`:

- `Text`
- `Unit`
- `Token`
- `Frequency`
- `Match`

Proposed new entities:

- `FeatureSet`: stable features for tokens, to separate display text from normalized text, reduce database size
- `MatchSet`: Group matches together by the conditions of the match

Proposed changes to existing entities:

- Add `line` and `phrase` fields to `Token` that point to the corresponding `Unit` entries in the database
- Move all features (`form`, `lemmata`, `semantic`, `sound`) from `Token` to `FeatureSet` and add `feature` field to `Token`

These updates will allow us to use the [MongoDB aggregation pipeline](https://docs.mongodb.com/manual/core/aggregation-pipeline/) more effectively and to reduce space used in the database recording information about tokens. I think it's possible to compute all matches entirely within MongoDB under this scheme.

Do these proposed changes work with the current REST API, or else would it be easy to update to meet them? Are there any other changes that I need to include?

**Comment by nOkuda** [comment]
The biggest question for the REST API is how to handle arbitrary CTS URN subreferences.

Let's see if your proposed changes provide the speedup we want.  If they do, we can start worrying about how to make the CTS URN magic happen.

**Comment by nOkuda** [comment]
I've been thinking a little more about this (with respect to how to make arbitrary CTS URN referencing work), and I've decided there is something I'd like to happen.  It would be nice if `Token` and `Unit` had CTS URN references associated with them.  This shouldn't be too hard for lines, given that `.tess` files are structured around lines.  And to make searching easier, it might be worth splitting the work identification from the subreferencing:  make a `cts_urn` attribute that matches the CTS URN of the text it comes from and a `subreference` attribute to indicate more specifically the location of a given text span.

For example, consider the _Aeneid_.  The CTS URN for this work is `urn:cts:latinLit:phi0690.phi002`.  So the `Unit` corresponding to the first line of this work would have `self.cts_urn = 'urn:cts:latinLit:phi0690.phi002'` and `self.subreference = '1.1'`.  For the first `Token`, same `self.cts_urn`, but `self.subreference = '1.1@[1]-1.1@[4]'`, since the first token is "Arma" (and I think I'm interpreting the [subreferencing documentation](https://www.homermultitext.org/hmt-doc/cite/cts-subreferences.html) correctly---i.e., 1-based indexing, with inclusive ends).

Phrases are trickier, and the only solution I can come up with is to fill in the information after the fact.

If it isn't immediately obvious to you how to do what I've explained above, I'll make the adjustments once you've merged your changes that implement what you've outlined above.

**Comment by jeffkinnison** [comment]
That should be perfectly fine, we just need to be able to split/merge CTS URNs. The only change I'd like to make is not explicitly storing the text's URN in every unit/token in the database. We currently reference texts from units and tokens by their database id (the '_id' field automatically assigned on insert), and this same scheme should hold for any intra-entity references. It's a bit faster for MongoDB, and we can use the aggregation pipeline to reconstruct entire CTS URNs if necessary.

Phrases are definitely the tricky part here. I think we can store them as line CTS URNs, though, since that can be resolved using subreferences.

**Comment by nOkuda** [comment]
Yes, referencing the `Text`'s `_id` field from the `Token`s and `Unit`s sounds good.  I had it in my mind that the search would be on an index of `cts_urn` of `Token` and `Unit`, but your approach allows us to ditch database upkeep at the expense of an extra query.  That sounds like a worthy tradeoff.

**Comment by nOkuda** [comment]
We've merged the aggregation pipeline to master, so this issue is complete.
